from enum import Enum


class AllureTag(str, Enum):

    REGRESSION = "REGRESSION"
    USERS = "USERS"
    AUTHENTICATION = "AUTHENTICATION"

    GET_ENTITY = "GET_ENTITY"
    GET_ENTITIES = "GET_ENTITIES"
    CREATE_ENTITY = "CREATE_ENTITY"
    PART_UPDATE_ENTITY = "PART_UPDATE_ENTITY"
    FULL_UPDATE_ENTITY = "FULL_UPDATE_ENTITY"
    DELETE_ENTITY = "DELETE_ENTITY"
    VALIDATE_ENTITY = "VALIDATE_ENTITY"
    SUCCESS_LOGIN = "SUCCESS_LOGIN"